resource_types:
- name: artifactory
  type: docker-image
  source:
    repository: emeraldsquad/artifactory-resource

resources:
- name: artifactory-repo
  type: artifactory
  source:  
  source: 
    api_key: ((artifactory-api-key))
    artifact_id: concourse-it
    group_id: io.microsamples.cd
    host: "http://172.18.0.1:8081/artifactory"
    repository_id: concourse-it-repo

- name: deploy-app-resource
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: ((cf-user))    
    passowrd: ((cf-password))
    organization: ((cf-org))    
    space: ((cf-space))
    skip_cert_check: true

jobs:
- name: trigger-when-new-file-is-added-to-artifactory
  plan:
  - get: artifactory-repo
    trigger: true
  - put: deploy-app-resource
    params:
      manifest: artifactory-repo/manifest.yml
      path: concourse-it.jar